=== SivaramPg/swapi.info/public/api/people/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"height": {
			"type": "string"
		},
		"mass": {
			"type": "string"
		},
		"hair_color": {
			"type": "string"
		},
		"skin_color": {
			"type": "string"
		},
		"eye_color": {
			"type": "string"
		},
		"birth_year": {
			"type": "string"
		},
		"gender": {
			"type": "string"
		},
		"homeworld": {
			"type": "string"
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"species": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"vehicles": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"starships": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"height",
		"mass",
		"hair_color",
		"skin_color",
		"eye_color",
		"birth_year",
		"gender",
		"homeworld",
		"films",
		"species",
		"vehicles",
		"starships",
		"created",
		"edited",
		"url"
	]
}

=== SivaramPg/swapi.info/public/api/people/68.json
{
  "name": "Bail Prestor Organa",
  "height": "191",
  "mass": "unknown",
  "hair_color": "black",
  "skin_color": "tan",
  "eye_color": "brown",
  "birth_year": "67BBY",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/2",
  "films": [
    "https://sw-api.sivaramp.com/api/films/5",
    "https://sw-api.sivaramp.com/api/films/6"
  ],
  "species": ["https://sw-api.sivaramp.com/api/species/1"],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T16:53:08.575000Z",
  "edited": "2014-12-20T21:17:50.463000Z",
  "url": "https://sw-api.sivaramp.com/api/people/68"
}

=== SivaramPg/swapi.info/public/api/people/9.json
{
  "name": "Biggs Darklighter",
  "height": "183",
  "mass": "84",
  "hair_color": "black",
  "skin_color": "light",
  "eye_color": "brown",
  "birth_year": "24BBY",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/1",
  "films": ["https://sw-api.sivaramp.com/api/films/1"],
  "species": [],
  "vehicles": [],
  "starships": ["https://sw-api.sivaramp.com/api/starships/12"],
  "created": "2014-12-10T15:59:50.509000Z",
  "edited": "2014-12-20T21:17:50.323000Z",
  "url": "https://sw-api.sivaramp.com/api/people/9"
}

=== SivaramPg/swapi.info/public/api/people/12.json
{
  "name": "Wilhuff Tarkin",
  "height": "180",
  "mass": "unknown",
  "hair_color": "auburn, grey",
  "skin_color": "fair",
  "eye_color": "blue",
  "birth_year": "64BBY",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/planets/21",
  "films": [
    "https://sw-api.sivaramp.com/films/1",
    "https://sw-api.sivaramp.com/films/6"
  ],
  "species": [],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-10T16:26:56.138000Z",
  "edited": "2014-12-20T21:17:50.330000Z",
  "url": "https://sw-api.sivaramp.com/people/12"
}
