=== SivaramPg/swapi.info/public/api/people/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"height": {
			"type": "string"
		},
		"mass": {
			"type": "string"
		},
		"hair_color": {
			"type": "string"
		},
		"skin_color": {
			"type": "string"
		},
		"eye_color": {
			"type": "string"
		},
		"birth_year": {
			"type": "string"
		},
		"gender": {
			"type": "string"
		},
		"homeworld": {
			"type": "string"
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"species": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"vehicles": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"starships": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"height",
		"mass",
		"hair_color",
		"skin_color",
		"eye_color",
		"birth_year",
		"gender",
		"homeworld",
		"films",
		"species",
		"vehicles",
		"starships",
		"created",
		"edited",
		"url"
	]
}

=== SivaramPg/swapi.info/public/api/people/61.json
{
  "name": "Cord√©",
  "height": "157",
  "mass": "unknown",
  "hair_color": "brown",
  "skin_color": "light",
  "eye_color": "brown",
  "birth_year": "unknown",
  "gender": "female",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/8",
  "films": ["https://sw-api.sivaramp.com/api/films/5"],
  "species": [],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T11:11:39.630000Z",
  "edited": "2014-12-20T21:17:50.449000Z",
  "url": "https://sw-api.sivaramp.com/api/people/61"
}

=== SivaramPg/swapi.info/public/api/people/31.json
{
  "name": "Nien Nunb",
  "height": "160",
  "mass": "68",
  "hair_color": "none",
  "skin_color": "grey",
  "eye_color": "black",
  "birth_year": "unknown",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/33",
  "films": ["https://sw-api.sivaramp.com/api/films/3"],
  "species": ["https://sw-api.sivaramp.com/api/species/10"],
  "vehicles": [],
  "starships": ["https://sw-api.sivaramp.com/api/starships/10"],
  "created": "2014-12-18T11:26:18.541000Z",
  "edited": "2014-12-20T21:17:50.371000Z",
  "url": "https://sw-api.sivaramp.com/api/people/31"
}

=== SivaramPg/swapi.info/public/api/people/4.json
{
  "name": "Darth Vader",
  "height": "202",
  "mass": "136",
  "hair_color": "none",
  "skin_color": "white",
  "eye_color": "yellow",
  "birth_year": "41.9BBY",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/1",
  "films": [
    "https://sw-api.sivaramp.com/api/films/1",
    "https://sw-api.sivaramp.com/api/films/2",
    "https://sw-api.sivaramp.com/api/films/3",
    "https://sw-api.sivaramp.com/api/films/6"
  ],
  "species": [],
  "vehicles": [],
  "starships": ["https://sw-api.sivaramp.com/api/starships/13"],
  "created": "2014-12-10T15:18:20.704000Z",
  "edited": "2014-12-20T21:17:50.313000Z",
  "url": "https://sw-api.sivaramp.com/api/people/4"
}

=== SivaramPg/swapi.info/public/api/people/6.json
{
  "name": "Owen Lars",
  "height": "178",
  "mass": "120",
  "hair_color": "brown, grey",
  "skin_color": "light",
  "eye_color": "blue",
  "birth_year": "52BBY",
  "gender": "male",
  "homeworld": "https://swapi.info/api/planets/1",
  "films": [
    "https://swapi.info/api/films/1",
    "https://swapi.info/api/films/5",
    "https://swapi.info/api/films/6"
  ],
  "species": [],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-10T15:52:14.024000Z",
  "edited": "2014-12-20T21:17:50.317000Z",
  "url": "https://swapi.info/api/people/6"
}

=== SivaramPg/swapi.info/public/api/people/67.json
{
  "name": "Dooku",
  "height": "193",
  "mass": "80",
  "hair_color": "white",
  "skin_color": "fair",
  "eye_color": "brown",
  "birth_year": "102BBY",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/52",
  "films": [
    "https://sw-api.sivaramp.com/api/films/5",
    "https://sw-api.sivaramp.com/api/films/6"
  ],
  "species": ["https://sw-api.sivaramp.com/api/species/1"],
  "vehicles": ["https://sw-api.sivaramp.com/api/vehicles/55"],
  "starships": [],
  "created": "2014-12-20T16:52:14.726000Z",
  "edited": "2014-12-20T21:17:50.462000Z",
  "url": "https://sw-api.sivaramp.com/api/people/67"
}

=== SivaramPg/swapi.info/public/api/people/60.json
{
  "name": "Gregar Typho",
  "height": "185",
  "mass": "85",
  "hair_color": "black",
  "skin_color": "dark",
  "eye_color": "brown",
  "birth_year": "unknown",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/planets/8",
  "films": ["https://sw-api.sivaramp.com/films/5"],
  "species": [],
  "vehicles": [],
  "starships": ["https://sw-api.sivaramp.com/starships/39"],
  "created": "2014-12-20T11:10:10.381000Z",
  "edited": "2014-12-20T21:17:50.445000Z",
  "url": "https://sw-api.sivaramp.com/people/60"
}

=== SivaramPg/swapi.info/public/api/people/47.json
{
  "name": "Ratts Tyerel",
  "height": "79",
  "mass": "15",
  "hair_color": "none",
  "skin_color": "grey, blue",
  "eye_color": "unknown",
  "birth_year": "unknown",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/planets/38",
  "films": ["https://sw-api.sivaramp.com/films/4"],
  "species": ["https://sw-api.sivaramp.com/species/16"],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T09:53:15.086000Z",
  "edited": "2014-12-20T21:17:50.410000Z",
  "url": "https://sw-api.sivaramp.com/people/47"
}

=== SivaramPg/swapi.info/public/api/people/78.json
{
  "name": "Shaak Ti",
  "height": "178",
  "mass": "57",
  "hair_color": "none",
  "skin_color": "red, blue, white",
  "eye_color": "black",
  "birth_year": "unknown",
  "gender": "female",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/58",
  "films": [
    "https://sw-api.sivaramp.com/api/films/5",
    "https://sw-api.sivaramp.com/api/films/6"
  ],
  "species": ["https://sw-api.sivaramp.com/api/species/35"],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T18:44:01.103000Z",
  "edited": "2014-12-20T21:17:50.486000Z",
  "url": "https://sw-api.sivaramp.com/api/people/78"
}
