=== SivaramPg/swapi.info/public/api/people/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"height": {
			"type": "string"
		},
		"mass": {
			"type": "string"
		},
		"hair_color": {
			"type": "string"
		},
		"skin_color": {
			"type": "string"
		},
		"eye_color": {
			"type": "string"
		},
		"birth_year": {
			"type": "string"
		},
		"gender": {
			"type": "string"
		},
		"homeworld": {
			"type": "string"
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"species": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"vehicles": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"starships": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"height",
		"mass",
		"hair_color",
		"skin_color",
		"eye_color",
		"birth_year",
		"gender",
		"homeworld",
		"films",
		"species",
		"vehicles",
		"starships",
		"created",
		"edited",
		"url"
	]
}

=== SivaramPg/swapi.info/public/api/people/65.json
{
  "name": "Barriss Offee",
  "height": "166",
  "mass": "50",
  "hair_color": "black",
  "skin_color": "yellow",
  "eye_color": "blue",
  "birth_year": "40BBY",
  "gender": "female",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/51",
  "films": ["https://sw-api.sivaramp.com/api/films/5"],
  "species": ["https://sw-api.sivaramp.com/api/species/29"],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T16:46:40.440000Z",
  "edited": "2014-12-20T21:17:50.457000Z",
  "url": "https://sw-api.sivaramp.com/api/people/65"
}

=== SivaramPg/swapi.info/public/api/people/10.json
{
  "name": "Obi-Wan Kenobi",
  "height": "182",
  "mass": "77",
  "hair_color": "auburn, white",
  "skin_color": "fair",
  "eye_color": "blue-gray",
  "birth_year": "57BBY",
  "gender": "male",
  "homeworld": "https://swapi.info/api/planets/20",
  "films": [
    "https://swapi.info/api/films/1",
    "https://swapi.info/api/films/2",
    "https://swapi.info/api/films/3",
    "https://swapi.info/api/films/4",
    "https://swapi.info/api/films/5",
    "https://swapi.info/api/films/6"
  ],
  "species": [],
  "vehicles": ["https://swapi.info/api/vehicles/38"],
  "starships": [
    "https://swapi.info/api/starships/48",
    "https://swapi.info/api/starships/59",
    "https://swapi.info/api/starships/64",
    "https://swapi.info/api/starships/65",
    "https://swapi.info/api/starships/74"
  ],
  "created": "2014-12-10T16:16:29.192000Z",
  "edited": "2014-12-20T21:17:50.325000Z",
  "url": "https://swapi.info/api/people/10"
}

=== SivaramPg/swapi.info/public/api/people/51.json
{
  "name": "Mace Windu",
  "height": "188",
  "mass": "84",
  "hair_color": "none",
  "skin_color": "dark",
  "eye_color": "brown",
  "birth_year": "72BBY",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/planets/42",
  "films": [
    "https://sw-api.sivaramp.com/films/4",
    "https://sw-api.sivaramp.com/films/5",
    "https://sw-api.sivaramp.com/films/6"
  ],
  "species": [],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T10:12:30.846000Z",
  "edited": "2014-12-20T21:17:50.420000Z",
  "url": "https://sw-api.sivaramp.com/people/51"
}

=== SivaramPg/swapi.info/public/api/people/8.json
{
  "name": "R5-D4",
  "height": "97",
  "mass": "32",
  "hair_color": "n/a",
  "skin_color": "white, red",
  "eye_color": "red",
  "birth_year": "unknown",
  "gender": "n/a",
  "homeworld": "https://swapi.info/api/planets/1",
  "films": ["https://swapi.info/api/films/1"],
  "species": ["https://swapi.info/api/species/2"],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-10T15:57:50.959000Z",
  "edited": "2014-12-20T21:17:50.321000Z",
  "url": "https://swapi.info/api/people/8"
}

=== SivaramPg/swapi.info/public/api/people/57.json
{
  "name": "Yarael Poof",
  "height": "264",
  "mass": "unknown",
  "hair_color": "none",
  "skin_color": "white",
  "eye_color": "yellow",
  "birth_year": "unknown",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/48",
  "films": ["https://sw-api.sivaramp.com/api/films/4"],
  "species": ["https://sw-api.sivaramp.com/api/species/25"],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T10:34:48.725000Z",
  "edited": "2014-12-20T21:17:50.437000Z",
  "url": "https://sw-api.sivaramp.com/api/people/57"
}

=== SivaramPg/swapi.info/public/api/people/82.json
{
  "name": "Sly Moore",
  "height": "178",
  "mass": "48",
  "hair_color": "none",
  "skin_color": "pale",
  "eye_color": "white",
  "birth_year": "unknown",
  "gender": "female",
  "homeworld": "https://sw-api.sivaramp.com/planets/60",
  "films": [
    "https://sw-api.sivaramp.com/films/5",
    "https://sw-api.sivaramp.com/films/6"
  ],
  "species": [],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T20:18:37.619000Z",
  "edited": "2014-12-20T21:17:50.496000Z",
  "url": "https://sw-api.sivaramp.com/people/82"
}

=== SivaramPg/swapi.info/public/api/people/5.json
{
  "name": "Leia Organa",
  "height": "150",
  "mass": "49",
  "hair_color": "brown",
  "skin_color": "light",
  "eye_color": "brown",
  "birth_year": "19BBY",
  "gender": "female",
  "homeworld": "https://swapi.info/api/planets/2",
  "films": [
    "https://swapi.info/api/films/1",
    "https://swapi.info/api/films/2",
    "https://swapi.info/api/films/3",
    "https://swapi.info/api/films/6"
  ],
  "species": [],
  "vehicles": ["https://swapi.info/api/vehicles/30"],
  "starships": [],
  "created": "2014-12-10T15:20:09.791000Z",
  "edited": "2014-12-20T21:17:50.315000Z",
  "url": "https://swapi.info/api/people/5"
}

=== SivaramPg/swapi.info/public/api/people/76.json
{
  "name": "Wat Tambor",
  "height": "193",
  "mass": "48",
  "hair_color": "none",
  "skin_color": "green, grey",
  "eye_color": "unknown",
  "birth_year": "unknown",
  "gender": "male",
  "homeworld": "https://sw-api.sivaramp.com/api/planets/56",
  "films": ["https://sw-api.sivaramp.com/api/films/5"],
  "species": ["https://sw-api.sivaramp.com/api/species/33"],
  "vehicles": [],
  "starships": [],
  "created": "2014-12-20T17:53:52.607000Z",
  "edited": "2014-12-20T21:17:50.481000Z",
  "url": "https://sw-api.sivaramp.com/api/people/76"
}
